
language: java
jdk: openjdk11
sudo: false
script: "mvn cobertura:cobertura"
cache:
  directories:
    - "$HOME/.m2/repository"
after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token